version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12.14.0
    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: yarn test

      - persist_to_workspace:
          root: ~/repo
          paths: .

  deploy:
    docker:
      - image: circleci/node:12.14.0
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Authenticate with registry
          command: |
            echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" > ~/.npmrc
      - run:
          name: Publish package
          command: npm publish

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          context: npmPublish
          requires:
            - build
          filters:
            branches:
              only:
                - master
                - feature/SAM-2335
